#!/bin/bash

set -e
set -o pipefail

image="ghcr.io/connext/nxtp-router"
tag=$1

if [[ -z "$tag" ]]; then
  echo "Empty tag name"
  exit 1
fi

app_path="/home/connext/nxtp-router-docker-compose"
now=$(date +"%Y-%m-%d_%H-%M-%S-%p")
logfile="$app_path/logs/deploy_$now.log"

cd $app_path

mkdir -p logs
touch $logfile

{
echo "=== Date: $now"
echo ""

echo "=== Deploing now:"
echo "=== Image: $image"
echo "=== Tag: $tag"
echo ""

sed -i -e "s#.*ROUTER_VERSION=.*#ROUTER_VERSION=$tag#" .env

echo "=== Remove unused data"
docker system prune -f
docker system prune -af
echo ""

echo "=== Pull new image"
docker pull $image:$tag
echo ""

echo "=== Update containers"
docker-compose up -d
echo ""

sleep 5s

docker images
echo ""
docker ps -a
echo ""

} 2>&1 | tee -a "$logfile"

