{
 "title": "Host Stats",
 "tags": [ "Node-Exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_exporter_build_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Host Metrics \nThis dashboard shows host level metrics gathered from prometheus. Prometheus in turn scrapes the data from the node-exporter scripts deployed as part of the template. You should be able to dynamically adjust the scope of the graphs using the templating above."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.101:9090/graph#%5B%7B%22expr%22%3A%22node_load1%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222016-1-19%2020%3A15%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Node Procs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_procs_blocked{instance=~\"$node\"}",
     "legendFormat": "Blocked - {{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Binstance%3D%5C%2210.196.94.38%3A9100%5C%22%2Cmode!%3D%5C%22idle%5C%22%7D%5B1m%5D)%20*%20100)%20by%20(node_cpu)%20%2F8%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-16%207%3A10%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    },
    {
     "expr": "node_procs_running{instance=~\"$node\"}",
     "legendFormat": "Running - {{instance}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node\"} / 1048576",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22node_memory_MemAvailable%7Binstance%3D%5C%2210.196.94.100%3A9100%5C%22%7D%20%2F%201048576%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222016-1-16%207%3A11%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Comitted Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Committed_AS_bytes{instance=~\"$node\"} / 1048576",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22node_memory_Committed_AS%7Binstance%3D%5C%2210.196.94.38%3A9100%5C%22%7D%20%2F%201048576%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222016-1-16%207%3A13%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory Free",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Disk Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "sum(rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[30s])) by (instance)",
     "legendFormat": "{{instance}}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22rate(node_disk_read_time_ms%7Binstance%3D%5C%2210.196.94.100%3A9100%5C%22%2Cdevice!%3D%5C%22sr0%5C%22%7D%5B30s%5D)%22%2C%22range_input%22%3A%2286400s%22%2C%22end_input%22%3A%222016-1-7%2014%3A58%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_filesystem_free_bytes{instance=~\"$node\",mountpoint=\"/\"}",
     "prometheusLink": "http://10.196.94.100:9090/graph#%5B%7B%22expr%22%3A%22node_filesystem_free%7Binstance%3D%5C%2210.196.94.100%3A9100%5C%22%2Cmountpoint%3D%5C%22%2F%5C%22%7D%22%2C%22range_input%22%3A%2286400s%22%2C%22end_input%22%3A%222016-1-7%2014%3A58%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_netstat_IpExt_InOctets{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "In - Discards"
    },
    {
     "expr": "rate(node_netstat_IpExt_OutOctets{instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Out - Discards"
    },
    {
     "expr": "rate(node_network_receive_drop_total{device=\"eth0\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Eth0 Receive Drops"
    }
   ]
  }
 ]
}