{
 "title": "Host Stats Extended",
 "tags": [ "Node-Exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_exporter_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic CPU / Mem / Net Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "stat",
   "description": "System Load (1m avg)",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:.*\"} - node_boot_time_seconds{instance=~\"$node:.*\"}"
    }
   ]
  },
  {
   "title": "Used RootFS",
   "type": "stat",
   "description": "Used RootFS",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_filesystem_size_bytes{mountpoint=~\"/\",instance=~\"$node:.*\"} - node_filesystem_free_bytes{mountpoint=~\"/\",instance=~\"$node:.*\"}) * 100 ) / (node_filesystem_size_bytes{mountpoint=~\"/\",instance=~\"$node:.*\"})"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net Gauge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy Now",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:.*\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:.*\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:.*\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "description": "Used RAM Memory without swap and cache",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node:.*\"} - node_memory_MemFree_bytes{instance=~\"$node:.*\"} - node_memory_Cached_bytes{instance=~\"$node:.*\"}) / (node_memory_MemTotal_bytes{instance=~\"$node:.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:.*\"} - node_memory_SwapFree_bytes{instance=~\"$node:.*\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:.*\"} )) * 100"
    }
   ]
  },
  {
   "title": "CPU System Load (1m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node:.*\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:.*\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "Basic network info per interface.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "recv bytes {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:.*\"}[5m])",
     "legendFormat": "trans bytes {{device}} "
    }
   ]
  },
  {
   "title": "Basic CPU / Mem Graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum ( irate(node_cpu_seconds_total{mode!='idle',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Busy"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:.*\"}[5m]))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"} - node_memory_MemFree_bytes{instance=~\"$node:.*\"} - node_memory_Cached_bytes{instance=~\"$node:.*\"} - node_memory_Buffers_bytes{instance=~\"$node:.*\"} - node_memory_Slab_bytes{instance=~\"$node:.*\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:.*\"} - node_memory_SwapFree_bytes{instance=~\"$node:.*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Basic Filesystem Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "description": "Local filesystem usage",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"} / node_filesystem_size_bytes{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"} * 100)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem Size",
   "type": "gauge",
   "description": "Local filesystem sIze info",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:.*\",fstype=~\"xfs|ext4\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Memory Net Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "description": "CPU info",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='system',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='nice',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Idle - Waiting for something to happen"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='irq',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='softirq',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='steal',instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by (mode)(irate(node_cpu_guest_seconds_total{instance=~\"$node:.*\"}[5m]))",
       "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
      }
     ]
    },
    {
     "title": "Memory Stack",
     "type": "graph",
     "description": "Memory Stack",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$node:.*\"} - node_memory_MemFree_bytes{instance=~\"$node:.*\"} - node_memory_Buffers_bytes{instance=~\"$node:.*\"} - node_memory_Cached_bytes{instance=~\"$node:.*\"} - node_memory_Slab_bytes{instance=~\"$node:.*\"} - node_memory_PageTables_bytes{instance=~\"$node:.*\"} - node_memory_SwapCached_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Apps - Memory used by processes"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "PageTables - Memory dedicated to the lowest page table level"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "SwapCache - Swap used as cache memory"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Cache - Physical RAM used as cache memory"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Buffers - Physical RAM used for file buffers"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Unused - Free memory unasigned"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:.*\"} - node_memory_SwapFree_bytes{instance=~\"$node:.*\"})",
       "legendFormat": "Swap - Swap memory usage"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "I/O Usage Read / Write",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "successfully read bytes {{device}}"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "successfully written bytes {{device}}"
      }
     ]
    },
    {
     "title": "I/O Usage Times",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node:.*\"} [5m])",
       "legendFormat": "milliseconds spent doing I/Os {{device}}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "graph",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100- ((node_filesystem_avail_bytes{instance=~\"$node:.*\",device!~'rootfs',fstype!~\"tmpfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:.*\",device!~'rootfs',fstype!~\"tmpfs\"})",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Committed - The amount of memory presently allocated on the system"
      },
      {
       "expr": "node_memory_Mapped_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Mapped - Files which have been mmaped, such as libraries"
      },
      {
       "expr": "node_memory_Active_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
      },
      {
       "expr": "node_memory_Inactive_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "VmallocUsed - Memory of used virtual address space"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Commit Limit - Total amount of  memory currently available to be allocated on the system"
      },
      {
       "expr": "node_memory_Dirty_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Dirty - Memory which is waiting to get written back to the disk"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Harware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
      },
      {
       "expr": "node_memory_Unevictable_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Unevictable - Unevictable pages can't be swapped out for a variety of reasons"
      },
      {
       "expr": "node_memory_Shmem_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Shared mem - Total memory used by shared memory (shmem) and tmpfs"
      },
      {
       "expr": "node_memory_Mlocked_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "MLocked - Pages locked to memory using the mlock() system call"
      }
     ]
    },
    {
     "title": "Swap in/out",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      {
       "format": "none",
       "label": "pages per second in (+) / out (-)"
      }
     ],
     "targets": [
      {
       "expr": "irate(node_vmstat_pswpin{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "swap_in"
      },
      {
       "expr": "irate(node_vmstat_pswpout{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "swap_out"
      }
     ]
    },
    {
     "title": "Memory Active / Inactive File",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_Active_file_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Active File - File-backed memory on active LRU list"
      },
      {
       "expr": "node_memory_Inactive_file_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Inactive File - File-backed memory on inactive LRU list"
      }
     ]
    },
    {
     "title": "Memory Usage Vmalloc",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_VmallocChunk_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "VmallocChunk - Largest contiguous block of vmalloc area which is free"
      },
      {
       "expr": "node_memory_VmallocTotal_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "VmallocTotal - Total size of vmalloc memory area"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "VmallocUsed - Amount of vmalloc area which is used"
      }
     ]
    },
    {
     "title": "Memory Usage HugePages",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_HugePages_Free{instance=~\"$node:.*\"}",
       "legendFormat": "HugePages Free - Number of huge pages in the pool that are not yet allocated"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{instance=~\"$node:.*\"}",
       "legendFormat": "HugePages Reserved - Number of huge pages for                 which a commitment to allocate from the pool has been made,                 but no allocation has yet been made"
      },
      {
       "expr": "node_memory_HugePages_Surp{instance=~\"$node:.*\"}",
       "legendFormat": "HugePages Surp - Number of huge pages in                 the pool above the value in /proc/sys/vm/nr_hugepages"
      },
      {
       "expr": "node_memory_HugePages_Total{instance=~\"$node:.*\"}",
       "legendFormat": "HugePages - Total size of the pool of huge pages"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Hugepagesize - Huge Page size"
      }
     ]
    },
    {
     "title": "Memory DirectMap",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_DirectMap1G_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "DirectMap1G - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap2M_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "DirectMap2M - Amount of pages mapped as this size"
      },
      {
       "expr": "node_memory_DirectMap4k_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "DirectMap4K  - Amount of pages mapped as this size"
      }
     ]
    },
    {
     "title": "Memory Anon",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_AnonHugePages_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Anon Huge Pages - Non-file backed huge pages mapped into userspace page tables"
      },
      {
       "expr": "node_memory_AnonPages_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Anon Pages - Non-file backed pages mapped into userspace page tables"
      },
      {
       "expr": "node_memory_Active_anon_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Inactive Anon - Anonymous and swap cache on inactive LRU list, including tmpfs (shmem)"
      }
     ]
    },
    {
     "title": "Memory Writeback",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Writeback - Memory which is actively being written back to disk"
      },
      {
       "expr": "node_memory_WritebackTmp_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "WritebackTmp - Memory used by FUSE for temporary writeback buffers"
      }
     ]
    },
    {
     "title": "Memory Reclaimed",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_SReclaimable_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "SReclaimable - Part of Slab, that might be reclaimed, such as caches"
      },
      {
       "expr": "node_memory_SUnreclaim_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "SUnreclaim - Part of Slab, that cannot be reclaimed on memory pressure"
      }
     ]
    },
    {
     "title": "Memory NFS",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_NFS_Unstable_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "NFS Unstable - NFS pages sent to the server, but not yet commited to the storage"
      }
     ]
    }
   ]
  },
  {
   "title": "System Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Context Switches / Interrupts / Entropy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "repeat": "node",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Context switches"
      },
      {
       "expr": "irate(node_intr_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Interrupts"
      },
      {
       "expr": "node_entropy_available_bits{instance=~\"$node:.*\"}",
       "legendFormat": "Entropy"
      }
     ]
    },
    {
     "title": "System Load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "repeat": "node",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$node:.*\"}",
       "legendFormat": "Load 1m"
      },
      {
       "expr": "node_load5{instance=~\"$node:.*\"}",
       "legendFormat": "Load 5m"
      },
      {
       "expr": "node_load15{instance=~\"$node:.*\"}",
       "legendFormat": "Load 15m"
      }
     ]
    },
    {
     "title": "Processes State / Forks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{instance=~\"$node:.*\"}",
       "legendFormat": "Processes blocked waiting for I/O to complete"
      },
      {
       "expr": "node_procs_running{instance=~\"$node:.*\"}",
       "legendFormat": "Processes in runnable state"
      },
      {
       "expr": "increase(node_forks_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "Processes forks"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Max file descriptors"
      },
      {
       "expr": "process_open_fds{instance=~\"$node:.*\"}",
       "legendFormat": "Open file descriptors"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Resident memory size in bytes"
      },
      {
       "expr": "process_start_time_seconds{instance=~\"$node:.*\"}",
       "legendFormat": "Start time of the process since unix epoch in seconds"
      },
      {
       "expr": "process_virtual_memory_bytes{instance=~\"$node:.*\"}",
       "legendFormat": "Virtual memory size in bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk R/W",
     "type": "graph",
     "description": "The total number of bytes read / write successfully.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes", "label": "read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_written_bytes_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_written"
      }
     ]
    },
    {
     "title": "Disk IOs",
     "type": "graph",
     "description": "Total number of reads / writes completed successfully",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "IO/second read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk IOs weighted",
     "type": "graph",
     "description": "The weighted # of milliseconds spent doing I/Os. This field is incremented at each I/O start, I/O completion, I/O  merge, or read of these stats by the number of I/Os in progress times the number of milliseconds spent doing I/O since the last update of this field. This can provide an easy measure of both I/O completion time and the backlog that may be accumulating.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W miliseconds",
     "type": "graph",
     "description": "The total number of milliseconds spent by all reads / writes.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_time_seconds_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_read"
      },
      {
       "expr": "irate(node_disk_write_time_seconds_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_write"
      }
     ]
    },
    {
     "title": "Disk R/W Merged",
     "type": "graph",
     "description": "The total number of  reads merged. See https://www.kernel.org/doc/Documentation/iostats.txt.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_merged_read"
      },
      {
       "expr": "irate(node_disk_writes_merged_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_merged_write"
      }
     ]
    },
    {
     "title": "Disk IOs current in progress",
     "type": "graph",
     "description": "The number of I/Os currently in progress.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short", "label": "I/Os" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_now{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk R/W completed",
     "type": "graph",
     "description": "The total number of reads / writes completed successfully. See https://www.kernel.org/doc/Documentation/iostats.txt.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_reads_completed_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_completed_read"
      },
      {
       "expr": "irate(node_disk_writes_completed_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}_completed_write"
      }
     ]
    },
    {
     "title": "Milliseconds spent doing I/Os",
     "type": "graph",
     "description": "Milliseconds spent doing I/Os.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$node:.*\"}[5m])",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Open error file",
     "type": "graph",
     "description": "1 if there was an error opening or reading a file, 0 otherwise",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_textfile_scrape_error{instance=~\"$node:.*\"}",
       "legendFormat": "read error"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Filesystem space available",
     "type": "graph",
     "description": "Filesystem space available to non-root users in bytes. Filesystem free space in bytes. Filesystem read-only status. Filesystem size in bytes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=~\"$node:.*\",device!~'rootfs',fstype!~\"tmpfs\"}",
       "legendFormat": "Size - {{mountpoint}}"
      },
      {
       "expr": "node_filesystem_avail_bytes{instance=~\"$node:.*\",device!~'rootfs',fstype!~\"tmpfs\"}",
       "legendFormat": "Available - {{mountpoint}}"
      }
     ]
    },
    {
     "title": "File nodes",
     "type": "graph",
     "description": "Filesystem total file nodes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files{instance=~\"$node:.*\",fstype!~\"tmpfs\"}",
       "legendFormat": "Size - {{device}}"
      },
      {
       "expr": "node_filesystem_files{instance=~\"$node:.*\",fstype!~\"tmpfs\"} - node_filesystem_files_free{instance=~\"$node:.*\",fstype!~\"tmpfs\"}",
       "legendFormat": "Used - {{device}}"
      }
     ]
    },
    {
     "title": "File descriptor",
     "type": "graph",
     "description": "File descriptor statistics: allocated.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_filefd_maximum{instance=~\"$node:.*\"}",
       "legendFormat": "max open files"
      },
      {
       "expr": "node_filefd_allocated{instance=~\"$node:.*\"}",
       "legendFormat": "open files"
      }
     ]
    },
    {
     "title": "Filesystem in ReadOnly",
     "type": "graph",
     "description": "Filesystem read-only status.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_readonly{instance=~\"$node:.*\",device!~'rootfs'}",
       "legendFormat": "{{mountpoint}} ReadOnly"
      }
     ]
    }
   ]
  },
  {
   "title": "Network traffic Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "pps", "label": "Packets per second" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Detail",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "pps", "label": "Packets per second" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_compressed_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive compressed"
      },
      {
       "expr": "irate(node_network_transmit_compressed_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} transmit compressed"
      },
      {
       "expr": "irate(node_network_receive_errs_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} transmit errors"
      },
      {
       "expr": "irate(node_network_receive_drop_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} transmit drop"
      },
      {
       "expr": "irate(node_network_receive_fifo_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive fifo"
      },
      {
       "expr": "irate(node_network_transmit_fifo_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} transmit fifo"
      },
      {
       "expr": "irate(node_network_receive_multicast_total{instance=~\"$node.*\"}[5m])",
       "legendFormat": "{{device}} receive multicast"
      }
     ]
    },
    {
     "title": "NF Contrack",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none", "label": "Entries" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{instance=~\"$node.*\"}",
       "legendFormat": "nf conntrack entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{instance=~\"$node.*\"}",
       "legendFormat": "nf conntrack limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sockstat TCP",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_TCP_alloc{instance=~\"$node.*\"}",
       "legendFormat": "TCP_alloc"
      },
      {
       "expr": "node_sockstat_TCP_inuse{instance=~\"$node.*\"}",
       "legendFormat": "TCP_inuse"
      },
      {
       "expr": "node_sockstat_TCP_mem{instance=~\"$node.*\"}",
       "legendFormat": "TCP_mem"
      },
      {
       "expr": "node_sockstat_TCP_mem_bytes{instance=~\"$node.*\"}",
       "legendFormat": "TCP_mem_bytes"
      },
      {
       "expr": "node_sockstat_TCP_orphan{instance=~\"$node.*\"}",
       "legendFormat": "TCP_orphan"
      },
      {
       "expr": "node_sockstat_TCP_tw{instance=~\"$node.*\"}",
       "legendFormat": "TCP_tw"
      }
     ]
    },
    {
     "title": "Sockstat UDP",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "none", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_UDPLITE_inuse{instance=~\"$node.*\"}",
       "legendFormat": "UDPLITE_inuse"
      },
      {
       "expr": "node_sockstat_UDP_inuse{instance=~\"$node.*\"}",
       "legendFormat": "UDP_inuse"
      },
      {
       "expr": "node_sockstat_UDP_mem{instance=~\"$node.*\"}",
       "legendFormat": "UDP_mem"
      },
      {
       "expr": "node_sockstat_UDP_mem_bytes{instance=~\"$node.*\"}",
       "legendFormat": "UDP_mem_bytes"
      }
     ]
    },
    {
     "title": "Sockstat Used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_sockets_used{instance=~\"$node.*\"}",
       "legendFormat": "Sockets_used"
      }
     ]
    },
    {
     "title": "Sockstat FRAG / RAW",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none", "label": "sockets" }
     ],
     "targets": [
      {
       "expr": "node_sockstat_FRAG_inuse{instance=~\"$node.*\"}",
       "legendFormat": "FRAG_inuse"
      },
      {
       "expr": "node_sockstat_FRAG_memory{instance=~\"$node.*\"}",
       "legendFormat": "FRAG_memory"
      },
      {
       "expr": "node_sockstat_RAW_inuse{instance=~\"$node.*\"}",
       "legendFormat": "RAW_inuse"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Netstat IP Octets",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_IpExt_InOctets{instance=~\"$node..*\"}[5m])",
       "legendFormat": "InOctets"
      },
      {
       "expr": "irate(node_netstat_IpExt_OutOctets{instance=~\"$node..*\"}[5m])",
       "legendFormat": "OutOctets"
      }
     ]
    },
    {
     "title": "Netstat IP Forwarding",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Ip_Forwarding{instance=~\"$node..*\"}[5m])",
       "legendFormat": "Forwarding"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP Connections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{instance=~\"$node.*\"}",
       "legendFormat": "CurrEstab - Number of TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT"
      }
     ]
    },
    {
     "title": "TCP Segments",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "none", "label": "segments" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_InErrs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InErrs - Number of segments received in error (e.g., bad TCP checksums)"
      },
      {
       "expr": "irate(node_netstat_Tcp_InSegs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InSegs - Number of segments received, including those received in error. This count includes segments received on currently established connections"
      },
      {
       "expr": "irate(node_netstat_Tcp_OutSegs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "OutSegs - Number of segments sent, including those on current connections but excluding those containing only retransmitted octets"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "RetransSegs - Number of segments retransmitted - that is, the number of TCP segments transmitted containing one or more previously transmitted octets"
      }
     ]
    },
    {
     "title": "TCP Direct Transition",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "none", "label": "connections" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~\"$node.*\"}[5m])",
       "legendFormat": "ActiveOpens - TCP connections that have made a direct transition to the SYN-SENT state from the CLOSED state"
      },
      {
       "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~\"$node.*\"}[5m])",
       "legendFormat": "PassiveOpens - TCP connections that have made a direct transition to the SYN-RCVD state from the LISTEN state"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat TCP Linux MIPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TCP SynCookie",
     "type": "graph",
     "description": "No documentation found for this values more than the definition in the kernel source code: https://github.com/torvalds/linux/blob/master/include/uapi/linux/snmp.h",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesFailed{instance=~\"$node.*\"}[5m])",
       "legendFormat": "SyncookiesFailed -"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesRecv{instance=~\"$node.*\"}[5m])",
       "legendFormat": "SyncookiesRecv -"
      },
      {
       "expr": "irate(node_netstat_TcpExt_SyncookiesSent{instance=~\"$node.*\"}[5m])",
       "legendFormat": "SyncookiesSent -"
      }
     ]
    },
    {
     "title": "TCP DROPS",
     "type": "graph",
     "description": "No documentation found for this values more than the definition in the kernel source code: https://github.com/torvalds/linux/blob/master/include/uapi/linux/snmp.h",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{instance=~\"$node.*\"}[5m])",
       "legendFormat": "ListenDrops -"
      }
     ]
    },
    {
     "title": "TCP Retrans",
     "type": "graph",
     "description": "No documentation found for this values more than the definition in the kernel source code: https://github.com/torvalds/linux/blob/master/include/uapi/linux/snmp.h",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_TCPSynRetrans{instance=~\"$node.*\"}[5m])",
       "legendFormat": "TCPSynRetrans -"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat UDP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "UDP In/Out",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InDatagrams{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InDatagrams"
      },
      {
       "expr": "irate(node_netstat_Udp_OutDatagrams{instance=~\"$node.*\"}[5m])",
       "legendFormat": "OutDatagrams"
      }
     ]
    },
    {
     "title": "UDP Lite Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_UdpLite_InErrors{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InErrors"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_InErrors{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InErrors"
      }
     ]
    },
    {
     "title": "UDP NoPorts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Udp_NoPorts{instance=~\"$node.*\"}[5m])",
       "legendFormat": "NoPorts"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Netstat ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ICMP Msg ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InMsgs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InMsgs -  Messages which the entity received. Note that this counter includes all those counted by icmpInErrors"
      },
      {
       "expr": "irate(node_netstat_Icmp_OutMsgs{instance=~\"$node.*\"}[5m])",
       "legendFormat": "OutMsgs - Messages which this entity attempted to send. Note that this counter includes all those counted by icmpOutErrors"
      }
     ]
    },
    {
     "title": "ICMP Errors / Unreachable",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(node_netstat_Icmp_InErrors{instance=~\"$node.*\"}[5m])",
       "legendFormat": "InErrors - Messages which the entity received but determined as having ICMP-specific errors (bad ICMP checksums, bad length, etc.)"
      }
     ]
    }
   ]
  }
 ]
}