{
 "title": "NXTP Router Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Type", "query": { "query": "label_values(label)" } },
   { "name": "Validator", "query": { "query": "label_values(validators)" } }
  ]
 },
 "panels": [
  { "title": "Quick stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 12, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "<img width=\"183\" height=\"45\" src=\"https://connext.network/images/connext__Logo--WhiteText-MultiColor-p-500.png\">\n\n<div style=\"margin-top: 30px;\">\n<div style=\"font-weight: 800; font-size: 18px;\">The Interoperability Protocol of L2 Ethereum.</div>\n<div style=\"margin-top:5px;\">Connext is the leading protocol for fast, fully noncustodial transfers and contract calls between EVM-compatible systems.</div>\n<div style=\"margin-top:10px; font-weight: 800; font-size: 18px;\">Helpful Links</div>\n<div style=\"\">\n<ul>\n  <li><a href=\"https://docs.connext.network/\" target=\"_blank\">Docs</a></li>\n  <li><a href=\"https://explorer.connext.network/\" target=\"_blank\">Explorer</a></li>\n  <li><a href=\"https://discord.com/invite/VcNFQdKuxM\" target=\"_blank\">Discord</a></li>\n  <li><a href=\"https://twitter.com/connextnetwork\" target=\"_blank\">Twitter</a></li>\n</ul>\n</div>\n</div>\n"
   }
  },
  {
   "title": "Router Action",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_auction_attempt", "legendFormat": "Attempt" },
    { "expr": "router_auction_successful", "legendFormat": "Successful" },
    { "expr": "router_auction_failed  ", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Action Chance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_auction_chance", "legendFormat": "{{validators}}" }
   ]
  },
  {
   "title": "Router Action Chance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_onchain_liquidity", "legendFormat": "{{validators}}" }
   ]
  },
  {
   "title": "Router",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_onchain_liquidity", "legendFormat": "Onchain Liquidity" },
    { "expr": "router_fees", "legendFormat": "Fees" }
   ]
  },
  {
   "title": "Router Transfer",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_transfer_attempt", "legendFormat": "Attempt" },
    { "expr": "router_transfer_successful", "legendFormat": "Successful" },
    { "expr": "router_transfer_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Transfer Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "router_transfer_successful / router_transfer_attempt",
     "legendFormat": "{{validators}}"
    }
   ]
  },
  {
   "title": "Router Roi",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_roi", "legendFormat": "{{validators}}" }
   ]
  },
  {
   "title": "Router",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_transfer_volume", "legendFormat": "Transfer Volume" },
    { "expr": "router_gas_consumed", "legendFormat": "Gas Consumed" }
   ]
  },
  { "title": "Detail stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Router Action",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "string", "label": "Count" }
   ],
   "targets": [
    { "expr": "router_auction_attempt", "legendFormat": "Attempt" },
    { "expr": "router_auction_successful", "legendFormat": "Successful" },
    { "expr": "router_auction_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Action Change(%)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent", "label": "Count" }
   ],
   "targets": [
    { "expr": "router_auction_chance", "legendFormat": "Change(%)" }
   ]
  },
  {
   "title": "Router Transfer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "string", "label": "Count" }
   ],
   "targets": [
    { "expr": "router_transfer_attempt", "legendFormat": "Attempt" },
    { "expr": "router_transfer_successful", "legendFormat": "Successful" },
    { "expr": "router_transfer_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "string", "label": "Count" }
   ],
   "targets": [
    { "expr": "router_transfer_volume", "legendFormat": "Transfer Volume" },
    { "expr": "router_roi", "legendFormat": "Roi" }
   ]
  },
  {
   "title": "Router Action",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_auction_attempt", "legendFormat": "Attempt" },
    { "expr": "router_auction_successful", "legendFormat": "Successful" },
    { "expr": "router_auction_failed  ", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Transfer",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_transfer_attempt", "legendFormat": "Attempt" },
    { "expr": "router_transfer_successful", "legendFormat": "Successful" },
    { "expr": "router_transfer_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Auction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_auction_successful", "legendFormat": "Successful" },
    { "expr": "router_auction_failed", "legendFormat": "Failed" }
   ]
  },
  {
   "title": "Router Auction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "router_auction_attempt", "legendFormat": "Attempt" },
    { "expr": "router_auction_chance", "legendFormat": "Chance" }
   ]
  }
 ]
}